server:
  port: 8092
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/logs
      username: postgres
      password: 31121998
      driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog.xml
    enabled: true